### ISSUE TITLE
Native test suite (test/) does not build on Linux / gcc 13 at development

### ISSUE THREAD

**Issue by LegendaryDrogan** [uxjulia/CrossInk#729]
**Device:** Not device-specific (host build of `test/`)

**Affected Version:** `development` 9819e3d2

**EPUB Optimization:** No / Not Applicable

**Cache State:** No / Not Applicable

**File Provided:** Not Applicable

## Describe the Bug

On Linux with gcc 13.3 / libstdc++, `cmake --build` of the native suite fails in four targets. `ci.yml` does not build `test/`, so CI does not catch these.

| Target | Error | Cause |
| --- | --- | --- |
| `EpubTextGrayscaleTest` | `GfxRenderer.cpp:1998:23: error: 'floor' is not a member of 'std'`, `FontDecompressor.cpp:122:5: error: 'memcpy' was not declared in this scope` | Neither file includes `<cmath>` / `<cstring>`. The firmware build only gets them through arduino-esp32's `Arduino.h`, which the test stubs do not replicate. |
| `SectionPersistenceTest` | `pstl/glue_algorithm_defs.h:22:17: error: invalid use of incomplete type 'struct std::_ExecutionPolicy'` | `<algorithm>` and `<deque>` are first included under `#define class struct`. |
| `SectionPersistenceTest` (once that compiles) | `undefined reference to CssParser::SvHash::operator()` | `Section.cpp` needs `CssParser.cpp`, which the suite does not compile. |
| `ChapterHtmlSlimParserTest` | `undefined reference to vtable for ImageDimsProbe` | `ImageDimsProbe.cpp` is not in the suite (dependency added in 3f158189). |
| `BitmapResampleTest` | `Bitmap.cpp:3:10: fatal error: Logging.h: No such file or directory` | `Bitmap.cpp` includes `<Logging.h>` (since 7b4454fd); the suite has no stub. |

## Steps to Reproduce

1. `git checkout development` (9819e3d2) on Ubuntu 24.04 (gcc 13.3, CMake 3.28, Ninja)
2. `cmake -S test -B build -G Ninja -DCMAKE_BUILD_TYPE=Release`
3. `cmake --build build`

## Expected Behavior

The suite builds and `ctest --test-dir build` passes.

## Relevant Log Output

Patches for all of them are below, one commit per fix, and apply with `git am` on `development` 9819e3d2:

- `GfxRenderer.cpp` +`#include <cmath>`, `FontDecompressor.cpp` +`#include <cstring>`
- `section_persistence`: include `<algorithm>`/`<deque>` before the macros; add `CssParser.cpp` to the executable; drop the `loadFromCache()` stub it replaces
- `chapter_html_slim_parser`: add `ImageDimsProbe.cpp` to the executable
- `bitmap_resample`: add a no-op `stubs/Logging.h`

With all of them applied at 9819e3d2, the build succeeds and `ctest` passes 458/458. For the two include changes: `pio run -e x4-pro` succeeds before and after. Every loaded section is the same size (`.flash.text` 2,680,288 B, `.flash.rodata` 3,231,500 B, `.iram0.text` 79,499 B, `.dram0.data` 29,594 B), both objects keep the same `text` size, and `firmware.bin` stays 6,022,416 B. Only non-loaded debug info changes (+216 B in the ELF).

<details><summary>Patches (git format-patch, based on development 9819e3d2)</summary>

```diff
From 53cc26955ed7b62958be418292b0c33e113206cf Mon Sep 17 00:00:00 2001
From: LegendaryDrogan <98139046+LegendaryDrogan@users.noreply.github.com>
Date: Mon, 14 Sep 2026 09:38:08 -0600
Subject: [PATCH] fix: include <cmath> and <cstring> where std::floor and
 memcpy are used

GfxRenderer.cpp calls std::floor and FontDecompressor.cpp calls memcpy,
but neither file includes the standard header that declares them. The
firmware build only compiles because the Arduino-ESP32 core's Arduino.h
includes <cmath> and <string.h>: GfxRenderer.cpp reaches it through
HalGPIO.h and Logging.h, and FontDecompressor.cpp includes it directly.

The native EpubTextGrayscaleTest suite compiles both files against test
stubs that do not pull in those headers, so on gcc 13.3 / libstdc++ it
fails to build:

  GfxRenderer.cpp:1998:23: error: 'floor' is not a member of 'std'
  FontDecompressor.cpp:122:5: error: 'memcpy' was not declared in this scope

Include the headers directly. In the firmware build both are already
included through Arduino.h, so this does not change the firmware.

Co-Authored-By: Claude Opus 5 (1M context) <noreply@anthropic.com>
Claude-Session: https://claude.ai/code/session_01KfUjqBMvrvDvNKfobp82uU
---
 lib/EpdFont/FontDecompressor.cpp | 1 +
 lib/GfxRenderer/GfxRenderer.cpp  | 1 +
 2 files changed, 2 insertions(+)

diff --git a/lib/EpdFont/FontDecompressor.cpp b/lib/EpdFont/FontDecompressor.cpp
index b2d5a59e..c034edc9 100644
--- a/lib/EpdFont/FontDecompressor.cpp
+++ b/lib/EpdFont/FontDecompressor.cpp
@@ -5,6 +5,7 @@
 #include <Utf8.h>
 
 #include <cstdlib>
+#include <cstring>
 
 FontDecompressor::~FontDecompressor() { deinit(); }
 
diff --git a/lib/GfxRenderer/GfxRenderer.cpp b/lib/GfxRenderer/GfxRenderer.cpp
index 8314a56b..f60c5f6d 100644
--- a/lib/GfxRenderer/GfxRenderer.cpp
+++ b/lib/GfxRenderer/GfxRenderer.cpp
@@ -10,6 +10,7 @@
 #include <freertos/task.h>
 
 #include <algorithm>
+#include <cmath>
 
 #include "FontCacheManager.h"
 
-- 
2.43.0

```

```diff
From 74c63b0e9e56f213a6c0de70b05a01047574e6a2 Mon Sep 17 00:00:00 2001
From: LegendaryDrogan <98139046+LegendaryDrogan@users.noreply.github.com>
Date: Mon, 14 Sep 2026 09:39:57 -0600
Subject: [PATCH 1/3] test: fix section_persistence native suite build

SectionPersistenceTest fails to build on gcc 13.3 / libstdc++, for two
independent reasons.

It includes Section.h and ChapterHtmlSlimParser.h under
`#define class struct` / `#define private public`, and those headers are
the first to include <algorithm> (through the HalStorage.h stub) and
<deque> (through ParsedText.h). libstdc++'s `template <class _Tp>`
declarations are then parsed as forward-declared structs:

  pstl/glue_algorithm_defs.h:22:17: error: invalid use of incomplete type 'struct std::_ExecutionPolicy'
  bits/stl_deque.h:2377:18: error: invalid use of incomplete type 'struct std::_Tp'

Include both headers before the macros. Each one alone still fails.

With that fixed, the executable does not link. Section.cpp calls
CssParser::clear(), which needs CssParser::SvHash::operator() from
CssParser.cpp, and that source is not in the suite:

  undefined reference to `CssParser::SvHash::operator()(std::__cxx11::basic_string<...> const&) const'

Compile CssParser.cpp into the executable, as chapter_html_slim_parser
already does, and drop the CssParser::loadFromCache() stub, which would
otherwise be a duplicate definition.

Co-Authored-By: Claude Opus 5 (1M context) <noreply@anthropic.com>
Claude-Session: https://claude.ai/code/session_01KfUjqBMvrvDvNKfobp82uU
---
 test/section_persistence/CMakeLists.txt                  | 1 +
 test/section_persistence/SectionPersistenceLinkStubs.cpp | 2 --
 test/section_persistence/SectionPersistenceTest.cpp      | 4 ++++
 3 files changed, 5 insertions(+), 2 deletions(-)

diff --git a/test/section_persistence/CMakeLists.txt b/test/section_persistence/CMakeLists.txt
index 0d269880..bf659cf1 100644
--- a/test/section_persistence/CMakeLists.txt
+++ b/test/section_persistence/CMakeLists.txt
@@ -2,6 +2,7 @@ add_executable(SectionPersistenceTest
   SectionPersistenceTest.cpp
   SectionPersistenceLinkStubs.cpp
   ${REPO_ROOT}/lib/Epub/Epub/Section.cpp
+  ${REPO_ROOT}/lib/Epub/Epub/css/CssParser.cpp
 )
 
 target_include_directories(SectionPersistenceTest PRIVATE
diff --git a/test/section_persistence/SectionPersistenceLinkStubs.cpp b/test/section_persistence/SectionPersistenceLinkStubs.cpp
index c61ae2ab..00431e05 100644
--- a/test/section_persistence/SectionPersistenceLinkStubs.cpp
+++ b/test/section_persistence/SectionPersistenceLinkStubs.cpp
@@ -19,8 +19,6 @@ int Epub::getTocItemsCount() const { return 0; }
 int Epub::getTocIndexForSpineIndex(int) const { return -1; }
 bool Epub::readItemContentsToStream(const std::string&, Print&, size_t, bool) const { return false; }
 
-bool CssParser::loadFromCache() { return false; }
-
 void Hyphenator::setPreferredLanguage(const std::string&) {}
 
 ChapterHtmlSlimParser::~ChapterHtmlSlimParser() = default;
diff --git a/test/section_persistence/SectionPersistenceTest.cpp b/test/section_persistence/SectionPersistenceTest.cpp
index f310be4b..b38750ed 100644
--- a/test/section_persistence/SectionPersistenceTest.cpp
+++ b/test/section_persistence/SectionPersistenceTest.cpp
@@ -1,6 +1,10 @@
 #include <gtest/gtest.h>
 
+// Include standard headers before the class/private macros below: libstdc++
+// templates declared with `class` do not compile if first parsed under them.
+#include <algorithm>
 #include <cstdint>
+#include <deque>
 #include <memory>
 #include <string>
 #include <utility>
-- 
2.43.0


From a6212dbb04c03a045cfe0cc86c981d5b701d5746 Mon Sep 17 00:00:00 2001
From: LegendaryDrogan <98139046+LegendaryDrogan@users.noreply.github.com>
Date: Mon, 14 Sep 2026 09:38:08 -0600
Subject: [PATCH 2/3] test: link ImageDimsProbe into the
 chapter_html_slim_parser suite

ChapterHtmlSlimParser::startElement() uses ImageDimsProbe, but the
suite's executable does not compile ImageDimsProbe.cpp, so it fails to
link:

  undefined reference to `vtable for ImageDimsProbe'

Add the source to the executable, as CrossPoint's copy of this suite
already does.

Co-Authored-By: Claude Opus 5 (1M context) <noreply@anthropic.com>
Claude-Session: https://claude.ai/code/session_01KfUjqBMvrvDvNKfobp82uU
---
 test/chapter_html_slim_parser/CMakeLists.txt | 1 +
 1 file changed, 1 insertion(+)

diff --git a/test/chapter_html_slim_parser/CMakeLists.txt b/test/chapter_html_slim_parser/CMakeLists.txt
index f345a910..2b94ee74 100644
--- a/test/chapter_html_slim_parser/CMakeLists.txt
+++ b/test/chapter_html_slim_parser/CMakeLists.txt
@@ -4,6 +4,7 @@ add_executable(ChapterHtmlSlimParserTest
   ${REPO_ROOT}/lib/Epub/Epub/parsers/ChapterHtmlSlimParser.cpp
   ${REPO_ROOT}/lib/Epub/Epub/css/CssParser.cpp
   ${REPO_ROOT}/lib/Epub/Epub/ParsedText.cpp
+  ${REPO_ROOT}/lib/Epub/Epub/converters/ImageDimsProbe.cpp
   ${REPO_ROOT}/lib/Epub/Epub/htmlEntities.cpp
   ${REPO_ROOT}/lib/Utf8/Utf8.cpp
 )
-- 
2.43.0


From 25ededcc7a0601dd56037d2e0ced6eb1be0b0f76 Mon Sep 17 00:00:00 2001
From: LegendaryDrogan <98139046+LegendaryDrogan@users.noreply.github.com>
Date: Mon, 14 Sep 2026 09:43:33 -0600
Subject: [PATCH 3/3] test: add a Logging.h stub to the bitmap_resample suite

Bitmap.cpp now includes <Logging.h> and logs when the Floyd-Steinberg
ditherer cannot be allocated, but the bitmap_resample suite has no
Logging.h on its include path, so BitmapResampleTest fails to compile:

  lib/GfxRenderer/Bitmap.cpp:3:10: fatal error: Logging.h: No such file or directory

Add a no-op LOG_* stub, as the other suites that compile logging code
already do.

Co-Authored-By: Claude Opus 5 (1M context) <noreply@anthropic.com>
Claude-Session: https://claude.ai/code/session_01KfUjqBMvrvDvNKfobp82uU
---
 test/bitmap_resample/stubs/Logging.h | 5 +++++
 1 file changed, 5 insertions(+)
 create mode 100644 test/bitmap_resample/stubs/Logging.h

diff --git a/test/bitmap_resample/stubs/Logging.h b/test/bitmap_resample/stubs/Logging.h
new file mode 100644
index 00000000..7f91008a
--- /dev/null
+++ b/test/bitmap_resample/stubs/Logging.h
@@ -0,0 +1,5 @@
+#pragma once
+
+#define LOG_DBG(...) ((void)0)
+#define LOG_INF(...) ((void)0)
+#define LOG_ERR(...) ((void)0)
-- 
2.43.0

```

</details>

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01KfUjqBMvrvDvNKfobp82uU
